"""
Youth Camp — one-shot migration: Google Sheets (via Apps Script) → D1 SQL.

Usage
-----
1. Make sure your GAS web app is still deployed and you have a mentor token.
2. (Tokens are NOT exposed by the API — security.) Open your Google Sheet,
   download these two tabs as CSV next to this script:
       CountryTokens   → country_tokens.csv
       MentorTokens    → mentor_tokens.csv
   (Or skip them and mint new tokens after deploy. See worker/README.md.)
3. Run:
       python import_from_sheets.py --webapp <URL> --mentor <TOKEN> \\
              [--country-csv country_tokens.csv] \\
              [--mentor-csv mentor_tokens.csv] \\
              --out import.sql
4. Apply:
       cd worker
       wrangler d1 execute youthcamp --remote --file=../import.sql

The output SQL clears each table and re-inserts everything pulled from Sheets.
Run AFTER schema.sql (which creates tables) and INSTEAD OF seed.sql (which would
overwrite mid-game state).
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
import urllib.parse
import urllib.request
from pathlib import Path


def fetch(webapp: str, params: dict[str, str]) -> dict:
    sep = "&" if "?" in webapp else "?"
    url = webapp + sep + urllib.parse.urlencode(params)
    with urllib.request.urlopen(url, timeout=30) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    if not data.get("ok"):
        raise RuntimeError(f"API error for {params}: {data.get('error')}")
    return data


def sql_literal(v) -> str:
    if v is None or v == "":
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v).replace("'", "''")
    return f"'{s}'"


def row_values(row: dict, cols: list[str]) -> str:
    return "(" + ", ".join(sql_literal(row.get(c)) for c in cols) + ")"


def insert_many(
    table: str, cols: list[str], rows: list[dict],
    zero_if_blank: set[str] | None = None,
) -> list[str]:
    """Emit `DELETE FROM table; INSERT INTO table ...` for rows.
    `zero_if_blank` lists NOT NULL numeric columns where empty/missing → 0
    (Google Sheets returns "" for blank cells; would violate NOT NULL otherwise)."""
    out = [f"DELETE FROM {table};"]
    if not rows:
        return out
    if zero_if_blank:
        for r in rows:
            for c in zero_if_blank:
                if r.get(c) in (None, ""):
                    r[c] = 0
    chunks = []
    BATCH = 200  # D1 likes manageable statement sizes
    for i in range(0, len(rows), BATCH):
        batch = rows[i : i + BATCH]
        vals = ",\n  ".join(row_values(r, cols) for r in batch)
        chunks.append(
            f"INSERT INTO {table} ({', '.join(cols)}) VALUES\n  {vals};"
        )
    out.extend(chunks)
    return out


def read_csv(path: str | None) -> list[dict]:
    if not path:
        return []
    p = Path(path)
    if not p.exists():
        print(f"  ! CSV not found: {path} — skipping", file=sys.stderr)
        return []
    with p.open(encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--webapp", required=True, help="WEBAPP_URL from index.html")
    ap.add_argument("--mentor", required=True, help="Mentor token (any letter's)")
    ap.add_argument("--country-csv", help="CountryTokens CSV export")
    ap.add_argument("--mentor-csv", help="MentorTokens CSV export")
    ap.add_argument("--out", default="import.sql", help="Output SQL file")
    ap.add_argument("--log-limit", type=int, default=99999, help="Max log rows to import")
    args = ap.parse_args()

    print("→ fetching dumpData ...", file=sys.stderr)
    dump = fetch(args.webapp, {"mentor": args.mentor})
    print(
        f"  countries={len(dump.get('countries',[]))} "
        f"products={len(dump.get('products',[]))} "
        f"prices={len(dump.get('prices',[]))} "
        f"recipes={len(dump.get('recipes',[]))} "
        f"purchase_orders={len(dump.get('purchase_orders',[]))}",
        file=sys.stderr,
    )

    print("→ fetching logs ...", file=sys.stderr)
    logs_payload = fetch(args.webapp, {"mentor": args.mentor, "action": "logs", "limit": str(args.log_limit)})
    logs = logs_payload.get("logs", [])
    print(f"  log rows = {len(logs)}", file=sys.stderr)

    country_tokens = read_csv(args.country_csv)
    mentor_tokens = read_csv(args.mentor_csv)
    print(
        f"  country_tokens={len(country_tokens)} mentor_tokens={len(mentor_tokens)}",
        file=sys.stderr,
    )

    out: list[str] = [
        "-- Auto-generated by import_from_sheets.py — DO NOT hand-edit",
        "-- Replaces each table's contents with whatever was in Google Sheets.",
        "-- (D1 wraps the whole --file in a single transaction; no BEGIN needed.)",
        "",
    ]

    out.extend(insert_many(
        "countries",
        [
            "country_id", "name", "flag", "domain", "level",
            "coins", "asset", "love", "honor",
            "water", "oil", "wood", "metal", "electricity", "chips",
            "l1_orders", "l2_orders", "l3_orders", "l4_orders",
            "shipments", "no_fail_cards", "last_draw_at",
        ],
        dump.get("countries", []),
        zero_if_blank={
            "level", "coins", "asset", "love", "honor",
            "water", "oil", "wood", "metal", "electricity", "chips",
            "l1_orders", "l2_orders", "l3_orders", "l4_orders",
            "shipments", "no_fail_cards",
        },
    ))
    out.append("")

    out.extend(insert_many(
        "products",
        ["country_id", "name", "level", "qty"],
        dump.get("products", []),
        zero_if_blank={"level", "qty"},
    ))
    out.append("")

    out.extend(insert_many(
        "prices",
        ["item_type", "item_key", "unit_size", "price", "price_jp", "sell_price", "asset_value", "note"],
        dump.get("prices", []),
        zero_if_blank={"unit_size", "price", "sell_price", "asset_value"},
    ))
    out.append("")

    # config: GAS exposes value as raw — coerce to string for the TEXT column
    cfg_rows = [{"key": r.get("key"), "value": str(r.get("value", "")), "note": r.get("note")}
                for r in dump.get("config", [])]
    out.extend(insert_many("config", ["key", "value", "note"], cfg_rows))
    out.append("")

    out.extend(insert_many(
        "rd_prizes",
        ["type", "value", "weight", "label", "note"],
        dump.get("rd_prizes", []),
        zero_if_blank={"value", "weight"},
    ))
    out.append("")

    out.extend(insert_many(
        "love_table",
        ["love", "multiplier", "note"],
        dump.get("love_table", []),
        zero_if_blank={"love", "multiplier"},
    ))
    out.append("")

    out.extend(insert_many(
        "levelup",
        ["to_level", "key", "label", "need", "note"],
        dump.get("level_up", []),
        zero_if_blank={"to_level", "need"},
    ))
    out.append("")

    out.extend(insert_many(
        "recipes",
        [
            "name", "country", "level",
            "water", "oil", "wood", "metal", "electricity", "chips",
            "semi1", "semi2", "semi3", "semi4", "note",
        ],
        dump.get("recipes", []),
        zero_if_blank={"level", "water", "oil", "wood", "metal", "electricity", "chips"},
    ))
    out.append("")

    # purchase_orders: GAS returns Date objects serialized as ISO strings; status/created_at OK
    out.extend(insert_many(
        "purchase_orders",
        ["id", "country_id", "level", "product", "status",
         "created_at", "consumed_at", "mentor_apply", "mentor_consume"],
        dump.get("purchase_orders", []),
        zero_if_blank={"level"},
    ))
    out.append("")

    out.extend(insert_many(
        "log",
        ["timestamp", "mentor", "country_id", "event", "field",
         "delta", "before", "after", "detail", "reason"],
        logs,
    ))
    out.append("")

    if country_tokens:
        out.extend(insert_many("country_tokens", ["country_id", "token", "note"], country_tokens))
        out.append("")

    if mentor_tokens:
        out.extend(insert_many("mentor_tokens", ["mentor_id", "token", "note"], mentor_tokens))
        out.append("")

    Path(args.out).write_text("\n".join(out), encoding="utf-8")
    print(f"✓ wrote {args.out}", file=sys.stderr)
    print(f"  next: cd worker && wrangler d1 execute youthcamp --remote --file=../{args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
